
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
